# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51d91b5ab5216880b18e43748dea767af62fa2afa736e21eeb59ef91cb5435bbbf6834dbfd9465a07e82531b4b852530699515add1d1d447960dbbf5b7e407cc

test:
  secret_key_base: e205647553a4a76cc6e48b229de1392b4946801d184954561b7a5a8ca77a5e31a425aa87f36b5613d18b798d7ee2650a915bd0091c51dfabe906323736ded099

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
